version: "3.9"

services:
  api:
    build: .
    container_name: shift_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
